name: Release
on:
  push:
    tags:
      - v*.*.*
  # pull_request:
  #   branches:
  #     - master

jobs:
  goreleaser:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      -
        name: Build Dependencies (Linux)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update && sudo apt-get install gcc-aarch64-linux-gnu
      -
        if: matrix.platform == 'ubuntu-latest'
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist -f hack/goreleaser/linux.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        if: matrix.platform == 'windows-latest'
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist -f hack/goreleaser/windows.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        if: matrix.platform == 'ubuntu-latest'
        name: Upload assets
        uses: actions/upload-artifact@v2
        with:
          name: disass_linux
          path: dist/*
      -
        if: matrix.platform == 'windows-latest'
        name: Upload assets
        uses: actions/upload-artifact@v2
        with:
          name: disass_windows
          path: dist/*